FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /e-stock
   
# copy source
COPY . .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /e-stock  
COPY --from=build /e-stock/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "e-stock-view.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet e-stock-view.dll

CMD ASPNETCORE_URLS=http://*:$PORT dotnet e-stock-view.dll